export const ROUTES = {
  HOME: "/",
  LOG_IN: "/log-in",
  REGISTER: "/register",
  ADD_ARTICLE: "/addArticle",
  EDIT_ARTICLE: "/editArticle/:id",
  ARTICLE_DETAILS: "/article/:id",
  USER_DETAILS: "/user/:id",
  MY_PROFILE: "/myProfile",
  SETTINGS: "/settings",
  PAYMENT_METHODS: "/paymentMethods",
  ADD_PAYMENT: "/addPaymentMethod",
  ADMIN_HOME: "/admin/home",
  ADMIN_DASHBOARD: "/admin/dashboard",
  MY_CARTS: "/myCarts",
  CART_DETAILS: "/cart/:id",
  SUCCESS: "/success",
  CANCEL: "/cancel",
};
