export const countries = [
  {
    code: "AD",
    label: "Andorra",
    cities: [
      "Andorra la Vella",
      "Escaldes-Engordany",
      "Encamp",
      "Sant Julià de Lòria",
      "La Massana",
    ],
  },
  {
    code: "AE",
    label: "United Arab Emirates",
    cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah"],
  },
  {
    code: "AF",
    label: "Afghanistan",
    cities: ["Kabul", "Herat", "Mazar-i-Sharif", "Kandahar", "Jalalabad"],
  },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    cities: ["St. John's"],
  },
  {
    code: "AI",
    label: "Anguilla",
    cities: ["The Valley"],
  },
  {
    code: "AL",
    label: "Albania",
    cities: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier"],
  },
  {
    code: "AM",
    label: "Armenia",
    cities: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"],
  },
  {
    code: "AO",
    label: "Angola",
    cities: ["Luanda", "Huambo", "Lobito", "Benguela", "Kuito"],
  },
  {
    code: "AR",
    label: "Argentina",
    cities: [
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Mendoza",
      "San Miguel de Tucumán",
    ],
  },
  {
    code: "AS",
    label: "American Samoa",
    cities: ["Pago Pago", "Tafuna", "Nu'uuli", "Fagatogo", "Leone"],
  },
  {
    code: "AT",
    label: "Austria",
    cities: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  },
  {
    code: "AU",
    label: "Australia",
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  },
  {
    code: "AW",
    label: "Aruba",
    cities: ["Oranjestad"],
  },
  {
    code: "AX",
    label: "Åland Islands",
    cities: ["Mariehamn"],
  },
  {
    code: "AZ",
    label: "Azerbaijan",
    cities: ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran"],
  },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    cities: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  },
  {
    code: "BB",
    label: "Barbados",
    cities: ["Bridgetown", "Speightstown", "Oistins", "Holetown", "Bathsheba"],
  },
  {
    code: "BD",
    label: "Bangladesh",
    cities: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  },
  {
    code: "BE",
    label: "Belgium",
    cities: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"],
  },
  {
    code: "BF",
    label: "Burkina Faso",
    cities: [
      "Ouagadougou",
      "Bobo-Dioulasso",
      "Koudougou",
      "Ouahigouya",
      "Banfora",
    ],
  },
  {
    code: "BG",
    label: "Bulgaria",
    cities: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  },
  {
    code: "BH",
    label: "Bahrain",
    cities: ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali"],
  },
  {
    code: "BI",
    label: "Burundi",
    cities: ["Bujumbura", "Muyinga", "Gitega", "Ngozi", "Rutana"],
  },
  {
    code: "BJ",
    label: "Benin",
    cities: ["Porto-Novo", "Cotonou", "Parakou", "Djougou", "Bohicon"],
  },
  {
    code: "BL",
    label: "Saint Barthelemy",
    cities: ["Gustavia"],
  },
  {
    code: "BM",
    label: "Bermuda",
    cities: [
      "Hamilton",
      "St. George's",
      "Somerset Village",
      "Mangrove Bay",
      "Flatts Village",
    ],
  },
  {
    code: "BN",
    label: "Brunei Darussalam",
    cities: [
      "Bandar Seri Begawan",
      "Kuala Belait",
      "Seria",
      "Tutong",
      "Bangar",
    ],
  },
  {
    code: "BO",
    label: "Bolivia",
    cities: [
      "La Paz",
      "Sucre",
      "Santa Cruz de la Sierra",
      "Cochabamba",
      "Oruro",
    ],
  },
  {
    code: "BR",
    label: "Brazil",
    cities: [
      "São Paulo",
      "Rio de Janeiro",
      "Brasília",
      "Salvador",
      "Fortaleza",
    ],
  },
  {
    code: "BS",
    label: "Bahamas",
    cities: ["Nassau", "Freeport", "Lucaya", "West End", "Coopers Town"],
  },
  {
    code: "BT",
    label: "Bhutan",
    cities: ["Thimphu", "Phuntsholing", "Punakha", "Gelephu", "Jakar"],
  },
  {
    code: "BV",
    label: "Bouvet Island",
    cities: [],
  },
  {
    code: "BW",
    label: "Botswana",
    cities: [
      "Gaborone",
      "Francistown",
      "Molepolole",
      "Serowe",
      "Selibe Phikwe",
    ],
  },
  {
    code: "BY",
    label: "Belarus",
    cities: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Hrodna"],
  },
  {
    code: "BZ",
    label: "Belize",
    cities: [
      "Belize City",
      "San Ignacio",
      "Belmopan",
      "Orange Walk Town",
      "Dangriga",
    ],
  },
  {
    code: "CA",
    label: "Canada",
    cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton"],
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    cities: [],
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani"],
  },
  {
    code: "CF",
    label: "Central African Republic",
    cities: ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari"],
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    cities: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo"],
  },
  {
    code: "CH",
    label: "Switzerland",
    cities: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  },
  {
    code: "CI",
    label: "Cote d'Ivoire",
    cities: ["Abidjan", "Bouaké", "Yamoussoukro", "Daloa", "San-Pédro"],
  },
  {
    code: "CK",
    label: "Cook Islands",
    cities: ["Avarua", "Arutanga", "Amuri", "Atiu", "Mangaia"],
  },
  {
    code: "CL",
    label: "Chile",
    cities: [
      "Santiago",
      "Puente Alto",
      "Antofagasta",
      "Viña del Mar",
      "Valparaíso",
    ],
  },
  {
    code: "CM",
    label: "Cameroon",
    cities: ["Douala", "Yaoundé", "Garoua", "Kousséri", "Bamenda"],
  },
  {
    code: "CN",
    label: "China",
    cities: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chongqing"],
  },
  {
    code: "CO",
    label: "Colombia",
    cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
  },
  {
    code: "CR",
    label: "Costa Rica",
    cities: ["San José", "Limon", "San Francisco", "Alajuela", "Cartago"],
  },
  {
    code: "CU",
    label: "Cuba",
    cities: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo"],
  },
  {
    code: "CV",
    label: "Cabo Verde",
    cities: ["Praia", "Mindelo", "Santa Maria", "Espargos", "Porto Novo"],
  },
  {
    code: "CW",
    label: "Curaçao",
    cities: [
      "Willemstad",
      "Sint Michiel Liber",
      "Sint Jozefsdal",
      "Dorp Soto",
      "Fontein",
    ],
  },
  {
    code: "CX",
    label: "Christmas Island",
    cities: ["Flying Fish Cove"],
  },
  {
    code: "CY",
    label: "Cyprus",
    cities: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"],
  },
  {
    code: "CZ",
    label: "Czech Republic",
    cities: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
  },
  {
    code: "DE",
    label: "Germany",
    cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"],
  },
  {
    code: "DJ",
    label: "Djibouti",
    cities: ["Djibouti", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil"],
  },
  {
    code: "DK",
    label: "Denmark",
    cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  },
  {
    code: "DM",
    label: "Dominica",
    cities: ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut"],
  },
  {
    code: "DO",
    label: "Dominican Republic",
    cities: [
      "Santo Domingo",
      "Santiago de los Caballeros",
      "Santo Domingo Este",
      "San Pedro de Macorís",
      "La Romana",
    ],
  },
  {
    code: "DZ",
    label: "Algeria",
    cities: ["Algiers", "Oran", "Constantine", "Annaba", "Batna"],
  },
  {
    code: "EC",
    label: "Ecuador",
    cities: [
      "Quito",
      "Guayaquil",
      "Cuenca",
      "Santo Domingo de los Colorados",
      "Machala",
    ],
  },
  {
    code: "EE",
    label: "Estonia",
    cities: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"],
  },
  {
    code: "EG",
    label: "Egypt",
    cities: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said"],
  },
  {
    code: "EH",
    label: "Western Sahara",
    cities: ["Laayoune", "Dakhla", "Smara", "Boujdour", "El Aaiún"],
  },
  {
    code: "ER",
    label: "Eritrea",
    cities: ["Asmara", "Keren", "Massawa", "Assab", "Mendefera"],
  },
  {
    code: "ES",
    label: "Spain",
    cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
  },
  {
    code: "ET",
    label: "Ethiopia",
    cities: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Adama"],
  },
  {
    code: "FI",
    label: "Finland",
    cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  },
  {
    code: "FJ",
    label: "Fiji",
    cities: ["Suva", "Lautoka", "Nadi", "Labasa", "Ba"],
  },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    cities: ["Stanley"],
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    cities: ["Palikir", "Weno", "Colonia", "Tofol", "Nan Madol"],
  },
  {
    code: "FO",
    label: "Faroe Islands",
    cities: ["Tórshavn", "Klaksvík", "Runavík", "Fuglafjørður", "Vágur"],
  },
  {
    code: "FR",
    label: "France",
    cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  },
  {
    code: "GA",
    label: "Gabon",
    cities: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"],
  },
  {
    code: "GB",
    label: "United Kingdom",
    cities: ["London", "Birmingham", "Manchester", "Edinburgh", "Glasgow"],
  },
  {
    code: "GD",
    label: "Grenada",
    cities: ["St. George's", "Gouyave", "Grenville", "Victoria", "Sauteurs"],
  },
  {
    code: "GE",
    label: "Georgia",
    cities: ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Zugdidi"],
  },
  {
    code: "GF",
    label: "French Guiana",
    cities: [
      "Cayenne",
      "Matoury",
      "Saint-Laurent-du-Maroni",
      "Kourou",
      "Rémire-Montjoly",
    ],
  },
  {
    code: "GG",
    label: "Guernsey",
    cities: ["Saint Peter Port"],
  },
  {
    code: "GH",
    label: "Ghana",
    cities: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast"],
  },
  {
    code: "GI",
    label: "Gibraltar",
    cities: ["Gibraltar"],
  },
  {
    code: "GL",
    label: "Greenland",
    cities: ["Nuuk", "Sisimiut", "Ilulissat", "Qaqortoq", "Aasiaat"],
  },
  {
    code: "GM",
    label: "Gambia",
    cities: ["Banjul", "Serekunda", "Brikama", "Bakau", "Lamin"],
  },
  {
    code: "GN",
    label: "Guinea",
    cities: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Guéckédou"],
  },
  {
    code: "GP",
    label: "Guadeloupe",
    cities: [
      "Les Abymes",
      "Basse-Terre",
      "Le Gosier",
      "Sainte-Anne",
      "Petit-Bourg",
    ],
  },
  {
    code: "GQ",
    label: "Equatorial Guinea",
    cities: ["Malabo", "Bata", "Ebebiyín", "Aconibe", "Anisoc"],
  },
  {
    code: "GR",
    label: "Greece",
    cities: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    cities: [],
  },
  {
    code: "GT",
    label: "Guatemala",
    cities: [
      "Guatemala City",
      "Mixco",
      "Villa Nueva",
      "Quetzaltenango",
      "San Miguel Petapa",
    ],
  },
  {
    code: "GU",
    label: "Guam",
    cities: ["Hagåtña", "Dededo", "Tamuning", "Mangilao", "Barrigada"],
  },
  {
    code: "GW",
    label: "Guinea-Bissau",
    cities: ["Bissau", "Bafatá", "Gabú", "Bissora", "Bolama"],
  },
  {
    code: "GY",
    label: "Guyana",
    cities: ["Georgetown", "Linden", "New Amsterdam", "Bartica", "Skeldon"],
  },
  {
    code: "HK",
    label: "Hong Kong",
    cities: ["Hong Kong"],
  },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    cities: [],
  },
  {
    code: "HN",
    label: "Honduras",
    cities: [
      "Tegucigalpa",
      "San Pedro Sula",
      "Choloma",
      "La Ceiba",
      "El Progreso",
    ],
  },
  {
    code: "HR",
    label: "Croatia",
    cities: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  },
  {
    code: "HT",
    label: "Haiti",
    cities: [
      "Port-au-Prince",
      "Carrefour",
      "Delmas",
      "Pétion-Ville",
      "Port-de-Paix",
    ],
  },
  {
    code: "HU",
    label: "Hungary",
    cities: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  },
  {
    code: "ID",
    label: "Indonesia",
    cities: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
  },
  {
    code: "IE",
    label: "Ireland",
    cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  },
  {
    code: "IL",
    label: "Israel",
    cities: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  },
  {
    code: "IM",
    label: "Isle of Man",
    cities: ["Douglas", "Peel", "Castletown", "Ramsey", "Port Erin"],
  },
  {
    code: "IN",
    label: "India",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad"],
  },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    cities: [],
  },
  {
    code: "IQ",
    label: "Iraq",
    cities: ["Baghdad", "Basra", "Sulaymaniyah", "Erbil", "Najaf"],
  },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    cities: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz"],
  },
  {
    code: "IS",
    label: "Iceland",
    cities: [
      "Reykjavik",
      "Kopavogur",
      "Hafnarfjordur",
      "Akureyri",
      "Reykjanesbær",
    ],
  },
  {
    code: "IT",
    label: "Italy",
    cities: ["Rome", "Milan", "Naples", "Turin", "Palermo"],
  },
  {
    code: "JE",
    label: "Jersey",
    cities: ["Saint Helier"],
  },
  {
    code: "JM",
    label: "Jamaica",
    cities: [
      "Kingston",
      "New Kingston",
      "Spanish Town",
      "Portmore",
      "Montego Bay",
    ],
  },
  {
    code: "JO",
    label: "Jordan",
    cities: ["Amman", "Zarqa", "Irbid", "Russeifa", "Al-Salt"],
  },
  {
    code: "JP",
    label: "Japan",
    cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo"],
  },
  {
    code: "KE",
    label: "Kenya",
    cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  },
  {
    code: "KG",
    label: "Kyrgyzstan",
    cities: ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok"],
  },
  {
    code: "KH",
    label: "Cambodia",
    cities: [
      "Phnom Penh",
      "Siem Reap",
      "Sihanoukville",
      "Battambang",
      "Kampong Cham",
    ],
  },
  {
    code: "KI",
    label: "Kiribati",
    cities: [
      "South Tarawa",
      "Betio Village",
      "Bairiki Village",
      "Bikenibeu Village",
      "Teaoraereke Village",
    ],
  },
  {
    code: "KM",
    label: "Comoros",
    cities: ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo"],
  },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    cities: [
      "Basseterre",
      "Charlestown",
      "Dieppe Bay Town",
      "Half Way Tree",
      "Sandy Point Town",
    ],
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    cities: ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"],
  },
  {
    code: "KR",
    label: "Korea, Republic of",
    cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  },
  {
    code: "KW",
    label: "Kuwait",
    cities: [
      "Kuwait City",
      "Al Ahmadi",
      "Hawalli",
      "As Salimiyah",
      "Sabah as Salim",
    ],
  },
  {
    code: "KY",
    label: "Cayman Islands",
    cities: [
      "George Town",
      "West Bay",
      "Bodden Town",
      "East End",
      "North Side",
    ],
  },
  {
    code: "KZ",
    label: "Kazakhstan",
    cities: ["Nur-Sultan", "Almaty", "Karaganda", "Shymkent", "Aktobe"],
  },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    cities: ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Thakhek"],
  },
  {
    code: "LB",
    label: "Lebanon",
    cities: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
  },
  {
    code: "LC",
    label: "Saint Lucia",
    cities: ["Castries", "Vieux Fort", "Micoud", "Soufrière", "Gros Islet"],
  },
  {
    code: "LI",
    label: "Liechtenstein",
    cities: ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen"],
  },
  {
    code: "LK",
    label: "Sri Lanka",
    cities: ["Colombo", "Galkissa", "Moratuwa", "Jaffna", "Negombo"],
  },
  {
    code: "LR",
    label: "Liberia",
    cities: ["Monrovia", "Gbarnga", "Kakata", "Harper", "Buchanan"],
  },
  {
    code: "LS",
    label: "Lesotho",
    cities: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek"],
  },
  {
    code: "LT",
    label: "Lithuania",
    cities: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  },
  {
    code: "LU",
    label: "Luxembourg",
    cities: [
      "Luxembourg",
      "Esch-sur-Alzette",
      "Differdange",
      "Dudelange",
      "Ettelbruck",
    ],
  },
  {
    code: "LV",
    label: "Latvia",
    cities: ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala"],
  },
  {
    code: "LY",
    label: "Libya",
    cities: ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Al Bayda"],
  },
  {
    code: "MA",
    label: "Morocco",
    cities: ["Casablanca", "Rabat", "Fès", "Marrakesh", "Agadir"],
  },
  {
    code: "MC",
    label: "Monaco",
    cities: ["Monaco"],
  },
  {
    code: "MD",
    label: "Moldova, Republic of",
    cities: ["Chisinau", "Tiraspol", "Bălți", "Bender", "Rîbnița"],
  },
  {
    code: "ME",
    label: "Montenegro",
    cities: ["Podgorica", "Nikšić", "Herceg Novi", "Pljevlja", "Bijelo Polje"],
  },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    cities: ["Marigot", "Grand-Case", "Rambaud", "La Savane", "Orléans"],
  },
  {
    code: "MG",
    label: "Madagascar",
    cities: [
      "Antananarivo",
      "Toamasina",
      "Antsirabe",
      "Fianarantsoa",
      "Mahajanga",
    ],
  },
  {
    code: "MH",
    label: "Marshall Islands",
    cities: ["Majuro", "Kwajalein", "Ebeye", "Arno Atoll", "Jabat"],
  },
  {
    code: "MK",
    label: "North Macedonia",
    cities: ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo"],
  },
  {
    code: "ML",
    label: "Mali",
    cities: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes"],
  },
  {
    code: "MM",
    label: "Myanmar",
    cities: ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago"],
  },
  {
    code: "MN",
    label: "Mongolia",
    cities: ["Ulaanbaatar", "Erdenet", "Darhan", "Hovd", "Mörön"],
  },
  {
    code: "MO",
    label: "Macao",
    cities: ["Macao"],
  },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    cities: ["Saipan", "San Jose", "Garapan", "Tinian Island", "Agrihan"],
  },
  {
    code: "MQ",
    label: "Martinique",
    cities: [
      "Fort-de-France",
      "Le Lamentin",
      "Le Robert",
      "Sainte-Marie",
      "Ducos",
    ],
  },
  {
    code: "MR",
    label: "Mauritania",
    cities: ["Nouakchott", "Nouadhibou", "Kiffa", "Zouérat", "Atar"],
  },
  {
    code: "MS",
    label: "Montserrat",
    cities: ["Plymouth", "Brades", "Little Bay", "St. Peter's", "Salem"],
  },
  {
    code: "MT",
    label: "Malta",
    cities: ["Valletta", "Birkirkara", "Mosta", "Qormi", "Sliema"],
  },
  {
    code: "MU",
    label: "Mauritius",
    cities: [
      "Port Louis",
      "Beau Bassin-Rose Hill",
      "Vacoas-Phoenix",
      "Curepipe",
      "Quatre Bornes",
    ],
  },
  {
    code: "MV",
    label: "Maldives",
    cities: ["Malé", "Addu City", "Fuvahmulah", "Hithadhoo", "Kulhudhuffushi"],
  },
  {
    code: "MW",
    label: "Malawi",
    cities: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
  },
  {
    code: "MX",
    label: "Mexico",
    cities: [
      "Mexico City",
      "Iztapalapa",
      "Ecatepec de Morelos",
      "Guadalajara",
      "Puebla City",
    ],
  },
  {
    code: "MY",
    label: "Malaysia",
    cities: [
      "Kuala Lumpur",
      "Johor Bahru",
      "Ipoh",
      "Shah Alam",
      "Petaling Jaya",
    ],
  },
  {
    code: "MZ",
    label: "Mozambique",
    cities: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"],
  },
  {
    code: "NA",
    label: "Namibia",
    cities: ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund"],
  },
  {
    code: "NC",
    label: "New Caledonia",
    cities: ["Nouméa", "Mont-Dore", "Dumbéa", "Païta", "Wé"],
  },
  {
    code: "NE",
    label: "Niger",
    cities: ["Niamey", "Zinder", "Maradi", "Agadez", "Alaghsas"],
  },
  {
    code: "NF",
    label: "Norfolk Island",
    cities: ["Kingston"],
  },
  {
    code: "NG",
    label: "Nigeria",
    cities: ["Lagos", "Kano", "Ibadan", "Kaduna", "Port Harcourt"],
  },
  {
    code: "NI",
    label: "Nicaragua",
    cities: ["Managua", "León", "Masaya", "Chinandega", "Matagalpa"],
  },
  {
    code: "NL",
    label: "Netherlands",
    cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  },
  {
    code: "NO",
    label: "Norway",
    cities: ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen"],
  },
  {
    code: "NP",
    label: "Nepal",
    cities: ["Kathmandu", "Pokhara", "Patan", "Biratnagar", "Birganj"],
  },
  {
    code: "NR",
    label: "Nauru",
    cities: ["Yaren"],
  },
  {
    code: "NU",
    label: "Niue",
    cities: ["Alofi"],
  },
  {
    code: "NZ",
    label: "New Zealand",
    cities: ["Auckland", "Christchurch", "Wellington", "Hamilton", "Tauranga"],
  },
  {
    code: "OM",
    label: "Oman",
    cities: ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar"],
  },
  {
    code: "PA",
    label: "Panama",
    cities: ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján"],
  },
  {
    code: "PE",
    label: "Peru",
    cities: ["Lima", "Arequipa", "Callao", "Trujillo", "Chiclayo"],
  },
  {
    code: "PF",
    label: "French Polynesia",
    cities: ["Papeete", "Faaa", "Punaauia", "Pirae", "Mahina"],
  },
  {
    code: "PG",
    label: "Papua New Guinea",
    cities: ["Port Moresby", "Lae", "Arawa", "Mount Hagen", "Popondetta"],
  },
  {
    code: "PH",
    label: "Philippines",
    cities: ["Quezon City", "Manila", "Davao City", "Caloocan", "Cebu City"],
  },
  {
    code: "PK",
    label: "Pakistan",
    cities: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan"],
  },
  {
    code: "PL",
    label: "Poland",
    cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"],
  },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    cities: ["Saint-Pierre", "Miquelon-Langlade", "Miquelon"],
  },
  {
    code: "PN",
    label: "Pitcairn",
    cities: ["Adamstown"],
  },
  {
    code: "PR",
    label: "Puerto Rico",
    cities: ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas"],
  },
  {
    code: "PS",
    label: "Palestine, State of",
    cities: ["Gaza City", "Rafah", "Khan Yunis", "Jabalia", "Hebron"],
  },
  {
    code: "PT",
    label: "Portugal",
    cities: ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra"],
  },
  {
    code: "PW",
    label: "Palau",
    cities: ["Ngerulmud", "Koror", "Melekeok", "Kloulklubed", "Imeong"],
  },
  {
    code: "PY",
    label: "Paraguay",
    cities: [
      "Asunción",
      "Ciudad del Este",
      "San Lorenzo",
      "Capiatá",
      "Lambaré",
    ],
  },
  {
    code: "QA",
    label: "Qatar",
    cities: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor"],
  },
  {
    code: "RE",
    label: "Réunion",
    cities: [
      "Saint-Denis",
      "Saint-Paul",
      "Le Tampon",
      "Saint-Pierre",
      "Le Port",
    ],
  },
  {
    code: "RO",
    label: "Romania",
    cities: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  },
  {
    code: "RS",
    label: "Serbia",
    cities: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  },
  {
    code: "RU",
    label: "Russian Federation",
    cities: [
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Nizhny Novgorod",
    ],
  },
  {
    code: "RW",
    label: "Rwanda",
    cities: ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi"],
  },
  {
    code: "SA",
    label: "Saudi Arabia",
    cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Sulţānah"],
  },
  {
    code: "SB",
    label: "Solomon Islands",
    cities: ["Honiara", "Gizo", "Auki", "Kirakira", "Munda"],
  },
  {
    code: "SC",
    label: "Seychelles",
    cities: [
      "Victoria",
      "Anse Boileau",
      "Beau Vallon",
      "Takamaka",
      "Anse Royale",
    ],
  },
  {
    code: "SD",
    label: "Sudan",
    cities: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "Al-Ubayyid"],
  },
  {
    code: "SE",
    label: "Sweden",
    cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  },
  {
    code: "SG",
    label: "Singapore",
    cities: ["Singapore"],
  },
  {
    code: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    cities: ["Georgetown", "Jamestown", "Edinburgh of the Seven Seas"],
  },
  {
    code: "SI",
    label: "Slovenia",
    cities: ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje"],
  },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    cities: ["Longyearbyen", "Barentsburg", "Ny-Ålesund"],
  },
  {
    code: "SK",
    label: "Slovakia",
    cities: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"],
  },
  {
    code: "SL",
    label: "Sierra Leone",
    cities: ["Freetown", "Bo", "Kenema", "Koidu Town", "Makeni"],
  },
  {
    code: "SM",
    label: "San Marino",
    cities: ["San Marino"],
  },
  {
    code: "SN",
    label: "Senegal",
    cities: ["Dakar", "Thiès", "Pikine", "Touba", "Rufisque"],
  },
  {
    code: "SO",
    label: "Somalia",
    cities: ["Mogadishu", "Hargeisa", "Berbera", "Kismayo", "Jamaame"],
  },
  {
    code: "SR",
    label: "Suriname",
    cities: [
      "Paramaribo",
      "Lelydorp",
      "Nieuw Nickerie",
      "Moengo",
      "Nieuw Amsterdam",
    ],
  },
  {
    code: "SS",
    label: "South Sudan",
    cities: ["Juba", "Wau", "Malakal", "Nimule", "Yambio"],
  },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    cities: ["São Tomé", "Neves", "Santana", "Trindade", "Guadalupe"],
  },
  {
    code: "SV",
    label: "El Salvador",
    cities: [
      "San Salvador",
      "Soyapango",
      "Santa Ana",
      "San Miguel",
      "Mejicanos",
    ],
  },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    cities: ["Philipsburg"],
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    cities: ["Damascus", "Aleppo", "Homs", "Latakia", "Al-Hasakah"],
  },
  {
    code: "SZ",
    label: "Eswatini",
    cities: ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Mhlume"],
  },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    cities: [
      "Cockburn Town",
      "Balfour Town",
      "Bottle Creek",
      "Blue Hills",
      "Five Cays",
    ],
  },
  {
    code: "TD",
    label: "Chad",
    cities: ["N'Djamena", "Moundou", "Sarh", "Abeche", "Kelo"],
  },
  {
    code: "TF",
    label: "French Southern Territories",
    cities: [],
  },
  {
    code: "TG",
    label: "Togo",
    cities: ["Lomé", "Sokodé", "Kara", "Atakpamé", "Dapaong"],
  },
  {
    code: "TH",
    label: "Thailand",
    cities: [
      "Bangkok",
      "Nonthaburi",
      "Nakhon Ratchasima",
      "Chiang Mai",
      "Hat Yai",
    ],
  },
  {
    code: "TJ",
    label: "Tajikistan",
    cities: ["Dushanbe", "Khujand", "Kŭlob", "Kŭrghonteppa", "Istaravshan"],
  },
  {
    code: "TK",
    label: "Tokelau",
    cities: [],
  },
  {
    code: "TL",
    label: "Timor-Leste",
    cities: ["Dili", "Maliana", "Lospalos", "Baucau", "Same"],
  },
  {
    code: "TM",
    label: "Turkmenistan",
    cities: ["Ashgabat", "Turkmenabat", "Daşoguz", "Mary", "Balkanabat"],
  },
  {
    code: "TN",
    label: "Tunisia",
    cities: ["Tunis", "Sfax", "Sousse", "Ettadhamen", "Kairouan"],
  },
  {
    code: "TO",
    label: "Tonga",
    cities: ["Nuku'alofa", "Neiafu", "Haveluloto", "Pangai", "Ohonua"],
  },
  {
    code: "TR",
    label: "Turkey",
    cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana"],
  },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    cities: [
      "Chaguanas",
      "San Fernando",
      "Port of Spain",
      "Arima",
      "Point Fortin",
    ],
  },
  {
    code: "TV",
    label: "Tuvalu",
    cities: ["Funafuti"],
  },
  {
    code: "TW",
    label: "Taiwan, Province of China",
    cities: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Banqiao"],
  },
  {
    code: "TZ",
    label: "Tanzania, United Republic of",
    cities: ["Dar es Salaam", "Dodoma", "Mwanza", "Zanzibar City", "Arusha"],
  },
  {
    code: "UA",
    label: "Ukraine",
    cities: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk"],
  },
  {
    code: "UG",
    label: "Uganda",
    cities: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja"],
  },
  {
    code: "UM",
    label: "United States Minor Outlying Islands",
    cities: [],
  },
  {
    code: "US",
    label: "United States",
    cities: ["New York City", "Los Angeles", "Chicago", "Houston", "Phoenix"],
  },
  {
    code: "UY",
    label: "Uruguay",
    cities: [
      "Montevideo",
      "Salto",
      "Ciudad de la Costa",
      "Paysandú",
      "Las Piedras",
    ],
  },
  {
    code: "UZ",
    label: "Uzbekistan",
    cities: ["Tashkent", "Namangan", "Samarkand", "Andijan", "Nukus"],
  },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    cities: ["Vatican City"],
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    cities: [
      "Kingstown",
      "Kingstown Park",
      "Georgetown",
      "Byera Village",
      "Biabou",
    ],
  },
  {
    code: "VE",
    label: "Venezuela",
    cities: ["Caracas", "Maracaibo", "Maracay", "Valencia", "Barquisimeto"],
  },
  {
    code: "VG",
    label: "Virgin Islands, British",
    cities: [
      "Road Town",
      "East End",
      "Spanish Town",
      "Charlotte Amalie",
      "West End",
    ],
  },
  {
    code: "VI",
    label: "Virgin Islands, U.S.",
    cities: [
      "Charlotte Amalie",
      "Anna's Retreat",
      "Charlotte Amalie West",
      "Frederiksted",
      "Cruz Bay",
    ],
  },
  {
    code: "VN",
    label: "Viet Nam",
    cities: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Biên Hòa"],
  },
  {
    code: "VU",
    label: "Vanuatu",
    cities: ["Port Vila", "Luganville", "Norsup", "Sola", "Lakatoro"],
  },
  {
    code: "WF",
    label: "Wallis and Futuna",
    cities: ["Mata-Utu"],
  },
  {
    code: "WS",
    label: "Samoa",
    cities: ["Apia", "Asau", "Mulifanua", "Leulumoega", "Satupa'itea"],
  },
  {
    code: "YE",
    label: "Yemen",
    cities: ["Sanaa", "Al Hudaydah", "Ta'izz", "Aden", "Ibb"],
  },
  {
    code: "YT",
    label: "Mayotte",
    cities: ["Mamoudzou", "Koungou", "Dzaoudzi", "Dembeni", "Sada"],
  },
  {
    code: "ZA",
    label: "South Africa",
    cities: [
      "Johannesburg",
      "Cape Town",
      "Durban",
      "Pretoria",
      "Port Elizabeth",
    ],
  },
  {
    code: "ZM",
    label: "Zambia",
    cities: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola"],
  },
  {
    code: "ZW",
    label: "Zimbabwe",
    cities: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"],
  },
];
